apiVersion: v2
name: podpilot
description: A Helm chart for deploying PodPilot across multiple clusters
type: application
version: 0.1.2
appVersion: "1.0.0"

dependencies:
  - name: opencost
    version: "1.33.1"
    repository: "https://opencost.github.io/opencost-helm-chart"
    condition: opencost.enabled
