# PodPilot Helm Chart Values

# ---------------------------------------------------------
# 1. CORE CREDENTIALS (Required)
# ---------------------------------------------------------
clusterName: "my-cluster"

workloadIdentity:
  clientId: "<CLIENT_ID_PROVIDED_BY_PODPILOT_TEAM>"
  tenantId: "<TENANT_ID_PROVIDED_BY_PODPILOT_TEAM>"
  subscriptionId: "<AZURE_SUBSCRIPTION_ID>"

database:
  uri: "<MONGO_DB_URI_PROVIDED_BY_PODPILOT_TEAM>"
  dbName: "" # Defaults to clusterName if left empty

basicAuth:
  enabled: true
  htpasswd: |-
    <HTPASSWD_PROVIDED_BY_PODPILOT_TEAM>

# ---------------------------------------------------------
# 2. INTERNAL BACKEND CONFIGURATION
# ---------------------------------------------------------
aiFoundry:
  endpoint: "<ENDPOINT_PROVIDED_BY_PODPILOT_TEAM>"
  deployment: "gpt-4o"
  # Authentication is handled securely via Azure Workload Identity.
  # No API key is required here.
  apiKey: ""

# ---------------------------------------------------------
# 3. ADVANCED CUSTOMIZATIONS (Optional)
# ---------------------------------------------------------
nameOverride: ""
fullnameOverride: ""
containerName: ""

image:
  repository: shazilhamzah/podpilot
  digest: "sha256:5343a377b2174e4490fa86f1478bdf0fb7b4f41aac717de3f6cc5c4841fa84cf"
  tag: latest # fallback if digest is removed
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

service:
  type: LoadBalancer
  port: 80
