{{- if .Values.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "podpilot.fullname" . }}-basic-auth
  labels:
    app.kubernetes.io/name: podpilot
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  auth: {{ .Values.basicAuth.htpasswd | b64enc | quote }}
{{- end }}
