{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "podpilot.fullname" . }}-registry
  labels:
    app.kubernetes.io/name: podpilot
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"podpilotregistry.azurecr.io\":{\"username\":\"00000000-0000-0000-0000-000000000000\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.imageCredentials (printf "00000000-0000-0000-0000-000000000000:%s" .Values.imageCredentials | b64enc) | b64enc }}
{{- end }}
