apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "podpilot.fullname" . }}
  labels:
    app.kubernetes.io/name: podpilot
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
